# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.CharField(db_column='Course_Id', default='Unknown', max_length=10, primary_key=True, serialize=False)),
                ('coursename', models.CharField(db_column='Course_Name', max_length=30)),
                ('coursetime', models.DateTimeField(db_column='Course_Time')),
                ('coursenum', models.IntegerField(db_column='Course_Max_Number', default=0)),
                ('courseinfo', models.CharField(db_column='Course_Information', default='Unknown', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.AutoField(db_column='Report_ID', primary_key=True, serialize=False)),
                ('score', models.IntegerField(db_column='Report_Score')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.CharField(db_column='Teacher_ID', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=30)),
                ('techername', models.CharField(db_column='Teacher_Name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_column='Student_ID', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=30)),
                ('realname', models.CharField(db_column='Student_Name', default='Unknown', max_length=10)),
                ('userPhone', models.IntegerField(db_column='Student_Phone', default='')),
                ('usersex', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], db_column='Student_Sex', default='Unknown', max_length=1)),
                ('email', models.EmailField(db_column='Email', default='blank', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Teacher'),
        ),
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.User'),
        ),
    ]
