# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20170423_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='teacherid',
        ),
        migrations.AddField(
            model_name='course',
            name='teacherid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.Teacher'),
            preserve_default=False,
        ),
    ]
