# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name=b'Score')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherid', models.CharField(max_length=30, verbose_name=b'TeacherID')),
                ('password', models.CharField(max_length=30, verbose_name=b'password')),
                ('techername', models.CharField(max_length=30, verbose_name=b'TeacherName')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseid',
            field=models.CharField(default=b'Unknown', max_length=10, verbose_name=b'Course_Id'),
        ),
        migrations.AddField(
            model_name='course',
            name='coursenum',
            field=models.IntegerField(default=0, verbose_name=b'Course_Max_Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=b'blank', max_length=254, verbose_name=b'Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, verbose_name=b'password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name=b'StudentName'),
        ),
        migrations.AddField(
            model_name='report',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Course'),
        ),
        migrations.AddField(
            model_name='report',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Teacher'),
        ),
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.User'),
        ),
    ]
