# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20170424_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='techername',
            new_name='teachername',
        ),
    ]
