# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20170425_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportid',
            field=models.AutoField(db_column='Report_ID', default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='score',
            field=models.IntegerField(db_column='Report_Score', default=''),
        ),
    ]
