# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20170425_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reportid',
        ),
        migrations.AddField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
