# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20170426_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='score',
            field=models.IntegerField(db_column='Report_Score', default=60),
        ),
    ]
